### ISSUE TITLE
RHEL7 support is not working

### ISSUE THREAD

**Issue by jblaine** [sous-chefs/mysql#234]
There is no RHEL7 "mysql" package offered by RH, so Chef obviously fails on `mysql::client` on RHEL7 due to the packages hardcoded in https://github.com/opscode-cookbooks/mysql/blob/master/libraries/provider_mysql_client_rhel.rb

However, check this out. Via root shell, `yum install mysql` picks `mariadb` ... but `package "mysql"` fails.

```
# yum install mysql
--> Running transaction check
---> Package mariadb.x86_64 1:5.5.37-1.el7_0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================
 Package              Arch                Version                       Repository                       Size
==============================================================================================================
Installing:
 mariadb              x86_64              1:5.5.37-1.el7_0              rhel-7-server-rpms              9.0 M

Transaction Summary
==============================================================================================================
Install  1 Package
...
```

```
# chef-apply -e 'package "mysql"'

Chef::Exceptions::Package
-------------------------
No version specified, and no candidate version available for mysql
...
Compiled Resource:
------------------
# Declared in /tmp/recipe-temporary-file20140923-26200-16cdxk4:1:in `run_chef_recipe'

package("mysql") do
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "mysql"
  cookbook_name "(chef-apply cookbook)"
  recipe_name "(chef-apply recipe)"
end
```

**Comment by jblaine** [comment]
@someara I realize there's a ton of grey area here, but I am finding that @adamhjk's suggestion to install MariaDB on RHEL 7+ is what the "more right" solution is as it relates to RHEL-the-OS and all of their stuff linked to MariaDB libs already. I just now had to uninstall the OS-desired `mariadb` and `mariadb-devel` to get `mysql_client` to converge as there's a package conflict with the `mysql-client-community` package otherwise :(

I suppose it boils down to the definition of the cookbook's real and necessary goal. IMO, it should be to be "Give me mysql (little 'm') functionality"

**Comment by someara** [comment]
This cookbook is scoped to the "MySQL Community Server", the one with the Oracle bits.
MariaDB is out of scope.

The fact that Redhat has decided the name install MariaDB when you type MySQL them creating a weird edge case for themselves, and the matter should be handled in the MariaDB cookbook.
