### ISSUE TITLE
add runit provider

### ISSUE THREAD

**Issue by hd-deman** [sous-chefs/mysql#297]
```
root@d529f24af1ad:/# sudo service mysql-default status
mysql-default: unrecognized service
```

my cookbook looks like this:

``` ruby
  mysql_service 'default' do
    version '5.5'
    initial_root_password node[:mysql][:server_root_password]
    action [:create, :start]
  end
```

run on ubuntu 14.04 inside docker container

**Comment by someara** [comment]
Don't specify the :start action when building containers.

Chef is trying to start it with Upstart, which isn't going to work inside
Docker.

-s

**Comment by hd-deman** [comment]
But what if I what to start it to run some other mysql related provisions. also how to run service manually?

**Comment by someara** [comment]
Try specifying
provider Chef::Provider::MysqlService::Sysvinit

**Comment by hd-deman** [comment]
specifying provider `Chef::Provider::MysqlService::Sysvinit` solve it.

**Comment by hd-deman** [comment]
stop working for me. 
```
  mysql_service 'default' do
    version '5.5'
    provider Chef::Provider::MysqlService::Sysvinit
    action [:create, :start]
  end
```

```
            ================================================================================
      Error executing action `enable` on resource 'service[default :start mysql-default]'
      ================================================================================

      Errno::ENOENT
      -------------
      No such file or directory - /sbin/insserv

      Resource Declaration:
      ---------------------
      # In /tmp/kitchen/cache/cookbooks/mysql/libraries/provider_mysql_service_sysvinit.rb

       27:           service "#{new_resource.name} :start #{mysql_name}" do
       28:             service_name mysql_name
       29:             provider Chef::Provider::Service::Init::Redhat if node['platform_family'] == 'redhat'
       30:             provider Chef::Provider::Service::Init::Insserv if node['platform_family'] == 'debian'
       31:             supports restart: true, status: true
       32:             action [:enable, :start]
       33:           end
       34:         end

````

any ideas?

**Comment by hd-deman** [comment]
@someara reopen pls

**Comment by someara** [comment]
Try Chef::Provider::Service::Init::Redhat

**Comment by someara** [comment]
The command that Upstart uses to start the process is found here:

https://github.com/chef-cookbooks/mysql/blob/master/templates/default/upstart/mysqld.erb#L21

Since Upstart doesn't work inside Docker, you can try to just call that directly

**Comment by hd-deman** [comment]
@someara thx. I try to use [baseimage-docker](https://github.com/phusion/baseimage-docker) as base image that use runit

**Comment by hd-deman** [comment]
Is supporting docker on the roadmap?

**Comment by someara** [comment]
There's nothing more for this cookbook to do to "support" Docker.

The :create action on mysql_service and mysql_config lay the bits out on
disk.

After that, Docker *really* want you to start the process externally from
the Dockerfile.

https://docs.docker.com/reference/builder/#run
https://docs.docker.com/reference/builder/#cmd

The Ubuntu service facility is Upstart, which cannot be used inside Docker.

If you want to run an alternative service manager as PID1 (daemontools,
runit, supervisor, etc), you're free to do so, but that's currently beyond
the scope of the resources shipped with this cookbook.

I'd recommend creating cookbook with provider Runit provider that
subclasses Chef::Provider::MysqlService

See here for examples:

https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_smf.rb
https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_systemd.rb
https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_sysvinit.rb
https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_upstart.rb

This may be added here in the future.

-s

**Comment by hd-deman** [comment]
@someara reopen it, please. I will try to make a PR that will add [runit](https://github.com/hw-cookbooks/runit) service for mysql.

**Comment by hd-deman** [comment]
```
  link "/sbin/insserv" do
    to "/usr/lib/insserv/insserv"
  end
```
this fix error `No such file or directory - /sbin/insserv`
