### ISSUE TITLE
MySql Minor Version Selection

### ISSUE THREAD

**Issue by bassrock** [sous-chefs/mysql#323]
I currently use the cookbook to develop for my AWS resources. RDS is currently at MySql Version 5.6.22. Is there a way to select a minor version for the cookbook to install. This makes sure developers do not use features by accident that are not supported on the live instance.

**Comment by aronwoost** [comment]
+1

**Comment by djmbm** [comment]
+1

**Comment by someara** [comment]
I'm open to collecting ideas on how this might be implemented

**Comment by djmbm** [comment]
Honestly, I'm not sure how package_version is used by the provider.

In theory this may even already handle it by passing in the full version, say... 5.6.22.

All of the versions/patchlevels exist in the repo:
http://repo.mysql.com/yum/mysql-5.6-community/el/6/x86_64/

**Comment by someara** [comment]
It shouldn't be too big of a stretch to get this working... it might even
clean up some of the uglier bits of helper code =)
-s
