### ISSUE TITLE
MySQL hangs during installation / configuration

### ISSUE THREAD

**Issue by cah-joseph-george** [sous-chefs/mysql#368]
I have a Ubuntu 14.04.2 VM created with packer. During the creation of the VM, I perform a default installation of MySQL 5.6. (I just use shell scripts to install and configure the VM.) Later on, I use Vagrant  with Chef-Zero to provision that VM. Using mysql cookbook 6.0.23 (and before) everything worked correctly. When I upgraded to v6.1.0, the provisioning hangs during the  "bash[default :create initial records] action run". The VM appears to be hung running the script created by the init_records_script. 

The 6.1 cookbook runs correctly on a vanilla vm. (But I encounter other unrelated errors later in my provisioning.) I've tried using 6.0.31 and 6.0.29, but both hang at the same point.

**Comment by someara** [comment]
How much ram are you giving your VMs?

**Comment by cah-josephgeorge** [comment]
1G of ram. 2 CPUs.

**Comment by someara** [comment]
Weird... I can't seem to reproduce this... mind taking a crack at debugging
the script?

If I had to guess, it's happening here:
https://github.com/chef-cookbooks/mysql/blob/ccb82794a7860dfcab098d5274968566905b1e4b/libraries/helpers.rb

Most likely waiting on this:
https://github.com/chef-cookbooks/mysql/blob/ccb82794a7860dfcab098d5274968566905b1e4b/libraries/helpers.rb#L148

... or something close.

ultimate Chef debug-fu is basically sticking

require 'pry' ; binding.pry

... interesting places and manually running chef-client

-s

**Comment by cah-josephgeorge** [comment]
I'll try to debug it. I was thinking it was blocking at the same location as well. I was also wondering if it was hitting some race condition.

**Comment by cah-josephgeorge** [comment]
After some debugging, I'm not sure why the code now fails or why it worked to begin with. The code appears to be hanging on:
[https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L181

When I inspect the VM during provisioning, the lock and pid file are still in /run/mysqld (from the initial installation configuration) and not yet in /run/mysql-default The cookbook does not appear to be finding the existing instance and shutting it down prior to doing its work. I updated my base VM to disable mysql from starting at boot and the provisioning then runs correctly.

I've looked at the diff between 6.0.23 and 6.0.29, but I don't see the changes that would've affected this.

**Comment by till** [comment]
I seem to have the same issue with 6.1.2. It seems that the "standard" mysql is stuck in a respawn loop according to upstart. Is there a documented way to either use that or to stop it?

It seemed to sometimes complete though.

**Comment by till** [comment]
Just as a heads up, after debugging around, the reason was a fubar'd upstart config. Once that happened, then you can't stop/restart the service without it being stuck. My problem seemed to be outdated MySQL configuration variables when moving from 5.1 (or so) to 5.6 and general struggles with upstart :trollface:.

Easiest way to fix was to destroy the VM and start from scratch.

**Comment by jcderose** [comment]
+1 I'm having the same issue with Test Kitchen 1.4.2, Chef 12.4.0, Ubuntu 14.04, and MySQL 5.5. (and 1 GB RAM, 2 CPUs in my VM)

I did not have the problem up to version 6.0.27 of the `mysql` cookbook, but started having the problem with version 6.0.28 and above.

**Comment by gsaslis** [comment]
+1 

Same hang issue here guys... I'm also on test kitchen 1.4.2, chef 12.6.0, ubuntu 14.04, mysql 5.6 and mysql cookbook version 6.1.2...

**Comment by dhoer** [comment]
I'm seeing the same thing consistently for ubuntu 14.04 on travis-ci: https://travis-ci.org/dhoer/chef-flywaydb/builds/106340999

**Comment by wiw-boldfield** [comment]
I just ran into this issue.  fwiw the issue I ran into was the socket location somewhere in the stack was expected to be:

`/var/run/mysql-default/mysqld.sock`

even though I was specifying something else explicitly in the `mysql_service` resource definition (where where `default` is resource name)..  I don't have time atm to chase it all the way down, but maybe this can solve the issue for someone else.
