### ISSUE TITLE
mysql_service provider should not change directory permissions on data_dir if already exists

### ISSUE THREAD

**Issue by et304383** [sous-chefs/mysql#376]
In my case, I'm trying to make a mysql_service which behaves identical to a fresh install of mysql without using the cookbook.  This means the data directory is /var/lib/mysql and the socket is /var/lib/mysql/mysql.sock

https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_base.rb#L118
By changing the directory permissions on data_dir to 750 (from 755) you prevent a non-sudo user from connecting as they cannot read the socket file.

I know this is a typical use case where one wants to convert to using the MySQL 6.x cookbook (despite your recommendation in the README to start from scratch) but changing the directory permissions on the data directory breaks the standard socket location access.

Please change the mode to 755 on the given line number.  At the very least, only run the resource if the directory does not already exist (so that the cookbook does not touch it at all).

**Comment by geleman** [comment]
My advice is move your socket file to the /tmp which can be done via the cookbook. Changing the permissions of the data directory to allow non-sudo users to access is a bad security practice.

**Comment by nkadel-skyhook** [comment]
Follow the RHEL package standard: put it in /var/ryn/mysql-[instance]. /tmp/ is a _nasty_ place to put  what should be a stable socket lasting the lifespan of the daemon, not of the client instance, and that is a subtle violation of the file system hierarchy.
