### ISSUE TITLE
Can't specify log locations outside of standard /var/log/mysql-<service_name>

### ISSUE THREAD

**Issue by et304383** [sous-chefs/mysql#385]
The mysql_service resource does not set the appropriate permissions on the log location folder.  Attempting to create the folder before in my recipe also does not work as the mysql user does not exist yet (since the yum package is installed by mysql_service which in turn creates the user).

The only way to get this to work is to install the package first through yum, create the directory, then invoke the mysql_service resource.

If the resource itself could set the appropriate permissions on the directories for the log files that would be awesome.

**Comment by nkadel-skyhook** [comment]
The simplest workaround is to have a wrapper cookbook that generates, and maintains, a symlink to /var/log/mysql_service, and to pre-create the "mysql" user. that's what I've been forced to do with /var/lib/mysql, along with opening permissions on /etc/mysqll-default and /etc/mysql-default/conf.d for legibility to all, and symlinks to from /etc/mysql-default/my.cnf to the bog-standard system expected location of /etc/my.cnf users. It's a hack, but it's workable.

**Comment by eric-tucker** [comment]
Any intention of fixing this issue @someara ?
