### ISSUE TITLE
Better documentation for mysql_config

### ISSUE THREAD

**Issue by acranox** [sous-chefs/mysql#387]
The documentation in the README for mysql_config implies that the config for 'foo' would be affiliated with the service 'foo', but in fact it will end up in /etc/mysql-default/conf.d/my_extra_settings.cnf
It would be clearer if the documentation included the usage of " instance 'foo'" for mysql_config

```
mysql_service 'foo' do
  port '3306'
  version '5.5'
  initial_root_password 'change me'
  action [:create, :start]
end

mysql_config 'foo' do
  source 'my_extra_settings.erb'
  notifies :restart, 'mysql_service[foo]'
  action :create
end
```

**Comment by sergiopatino** [comment]
this renders mysql_config useless since this is not an includedir in the my.cnf created for instance foo:

!includedir /etc/mysql-foo/conf.d

**Comment by douglask99x** [comment]
Following fix here resolved my issue. I also had some values in my template that were not applicable to server version and would cause restart of service to hang as well. In the end I was able to get it working

```mysql_service 'example' do
  initial_root_password mysql_user_password
  action [:create, :start]
end

mysql_config 'extra' do
  instance 'example'
  source 'extra.cnf.erb'
  notifies :restart, 'mysql_service[example]'
  action :create
end

https://github.com/chef-cookbooks/mysql/issues/374

**Comment by douglask99x** [comment]
Following fix here resolved my issue. I also had some values in my template that were not applicable to server version and would cause restart of service to hang as well. In the end I was able to get it working

``` mysql_service 'example' do
  initial_root_password mysql_user_password
  action [:create, :start]
end

mysql_config 'extra' do
  instance 'example'
  source 'extra.cnf.erb'
  notifies :restart, 'mysql_service[example]'
  action :create
end ```

**Comment by faizalzakaria** [comment]
Thats what im looking for @kyledouglas . THanks.
