### ISSUE TITLE
Features: Ability to override package names, Attribute that prevents repository management

### ISSUE THREAD

**Issue by mrmarbury** [sous-chefs/mysql#391]
Hi,

we currently have very special requirements regarding mysql packages here. So we would need a way to override the package names that this CB will install. The other thing is that we use a different way of managing repositories and currently there is no way to change that. So an attribute through which we can disable the creation of the mysql repository would be great and I think fairly easy to implement as well?

Cheers,
Stefan

**Comment by ramereth** [comment]
We no longer use attributes and I think this is allowed in the current form of the cookbook.
