### ISSUE TITLE
Deprecated features used - chef 12.7.2

### ISSUE THREAD

**Issue by jayaich** [sous-chefs/mysql#400]
> Deprecated features used!
> Default value false is invalid for property enable_utf8 of resource mysql_service. In Chef 13 this will  become an error: Option enable_utf8 must be a kind of [String]!  You passed false.. at 1 location:
> - /var/chef/cache/cookbooks/mysql/libraries/resource_mysql_service.rb:26:in `class:MysqlService'

Looking at libraries/resource_mysql_service.rb it seems that ':enable_utf8' should be kind of '[TrueClass, FalseClass]' rather than 'String':
`attribute :enable_utf8, :kind_of => [TrueClass, FalseClass], :default => false`

The definition of 'parsed_enable_utf8' (in the same file) should also be changed:
`def parsed_enable_utf8`
 `return enable_utf8 unless enable_utf8.nil?`
 `end`

**Comment by acoulton** [comment]
Looks like this is no longer relevant, the `enable_utf8` setting no longer exists AFAICS?

**Comment by ramereth** [comment]
I'm pretty sure this is no longer the case.
