### ISSUE TITLE
/sbin/service mysql-default reload does not work on RHEL or CentOS 6

### ISSUE THREAD

**Issue by nkadel-skyhook** [sous-chefs/mysql#402]
On RHEL 6 and CentOS 6, after configuring a new mysql-default instance, reloading the daemon fails.
- /etc/init.d/mysql-default reload # Works just fine
- /sbin/service mysql-default reload # fails with meswsages below:
  
  /sbin/service mysql-default reload
  /usr/bin/mysqladmin: connect to server at 'localhost' failed
  error: 'Access denied for user 'root'@'localhost' (using password: NO)'
  Reloading mysql-default [FAILED]

I think I've isolated it to this command run by /sbin/service:

```
env -i PATH=/sbin:/usr/sbin:/bin:/usr/bin TERM=xterm /etc/init.d/mysql-default reload
```

It loooks like the env command is clearing "HOME=/root", which is killing access to /root/.my.cnf. I'm not sure what the best way is to activate those stored credentials for the init script, but the easy workaround for cron scripts or other  tasks is to explicitly set "HOME=/root".

**Comment by AjeetK** [comment]
In the centos version which you are using, `systemctl` or `systemd` might not be installed. You may choose `sysvinit` or `upstart` as service manager. Here is an [example](http://jee-appy.blogspot.com/2017/01/mysql-service-manager-chef-amazon.html)

**Comment by nkadel-skyhook** [comment]
@AjeetK I wrote the ticket specifically for CentOS and RHEL 6, which do not support systemd. They're using sysvinit by default.

**Comment by ramereth** [comment]
We are no longer supporting EL6.
