### ISSUE TITLE
Root password not being set on MySQL 5.7.6 and above

### ISSUE THREAD

**Issue by cptcanuck** [sous-chefs/mysql#410]
Ran into an issue working with the cookbook - we'd set the initial_root_password variable, but when the DB came up, we couldn't login.

Looking in the logs, we found a randomly generated password, which is a new feature in Mysql 5.7.6+ (http://dev.mysql.com/doc/refman/5.7/en/default-privileges.html):

`As of MySQL 5.7.6, if you initialized the data directory manually using mysqld --initialize and followed the instructions in Section 2.10.1.1, “Initializing the Data Directory Manually Using mysqld”, you should have assigned a password to the initial account.`

When we connect to the database with that password, we are good.  This lead us to look at the "libraries/helpers.rb " file, specifically at def init_records_script.  In there, the 'my.sql' file is being created with the command 

`UPDATE mysql.user SET #{password_column_name}=PASSWORD('#{root_password}')#{password_expired} WHERE user = 'root';`

which when run on a MySQL 5.7.6+ install, results in an error:

`ERROR 1820 (HY000): You must reset your password using ALTER USER statement before executing this statement`

The correct statement for 5.7.6+ is

`ALTER USER 'root'@'localhost' IDENTIFIED BY '#{root_password}';`

http://dev.mysql.com/doc/refman/5.7/en/default-privileges.html

```
As of MySQL 5.7.6, use ALTER USER:

mysql> ALTER USER user IDENTIFIED BY 'new_password';
Before 5.7.6, use SET PASSWORD:

mysql> SET PASSWORD FOR user = PASSWORD('new_password');
```

Once we tested and put that into the library file, we ran into the next issue - when attempting to run the script, the default umask (0077) was creating the /tmp/mysql-name/my.cnf file with permissions that couldn't be re-read.  We addressed that by setting the permissions in the _def init_records_script_ block.

The end result is a functional database .. hurrah!

I started working out how to make the library handle this case, but I've run out of brain power and time.

I've got a new def that sets the string based on the version, but it's not ideal, because not all of 5.7 is the same - the functionality changes in 5.7.6+, but this code assumes all of 5.7 is the same.  Then I replaced the line in the SQL tmpfile with the variable, and finally do the chmod.  

``` ruby
@@ -160,6 +159,14 @@ module MysqlCookbook
       mysql_install_db_cmd
     end
 +    def password_set_command
+    #http://dev.mysql.com/doc/refman/5.7/en/default-privileges.html
+    #changes to how to assign root account passwords 
+      cmd = "UPDATE mysql.user SET #{password_column_name}=PASSWORD('#{root_password}')#{password_expired} WHERE user = 'root';"
+      cmd = "ALTER USER 'root'@'localhost' IDENTIFIED BY '#{root_password}';" if v57plus
+      cmd
+    end
+
     def init_records_script
       <<-EOS
         set -e
@@ -167,14 +174,15 @@ module MysqlCookbook
         mkdir /tmp/#{mysql_name}

         cat > /tmp/#{mysql_name}/my.sql <<-EOSQL
-UPDATE mysql.user SET #{password_column_name}=PASSWORD('#{root_password}')#{password_expired} WHERE user = 'root';
+#{password_set_command}
 DELETE FROM mysql.user WHERE USER LIKE '';
 DELETE FROM mysql.user WHERE user = 'root' and host NOT IN ('127.0.0.1', 'localhost');
 FLUSH PRIVILEGES;
 DELETE FROM mysql.db WHERE db LIKE 'test%';
 DROP DATABASE IF EXISTS test ;
 EOSQL
-
+       #the default umask on CentOS 7 breaks automation, so we have to set the perms nicer
+       chmod -R 777 /tmp/#{mysql_name}
        #{db_init}
        #{record_init}
```

I assume someone with some actual useful Ruby skills can improve this and make the logic work, but I wanted to pass this along in case anyone else has the same issue.

(edits to fight with Markdown)

**Comment by iennae** [comment]
@cptcanuck Wow! Thanks for all the sleuthing, detailed documentation and providing some working code. We'll take a look in the next few weeks and get this on the schedule for fixing.

**Comment by aight8** [comment]
Any update??

**Comment by tealice** [comment]
Any chance the referenced PR gets updated/patched? I modified the cookbook locally (and hard coded 5.7 for the mysql_server `version`) with the change and succeeded with a mysql 8.0 install. 

I think I'd have time to make some updates here (cmd, version parse), just not sure on the status of this issue/PR. Thanks!

**Comment by josephholsten** [comment]
@tealice do you think you could put that into a new PR for us? I'm a little confused about the resolution of https://github.com/sous-chefs/mysql/pull/518

**Comment by tealice** [comment]
Yeah, I should be able to get to it tomorrow or Friday, I'll reference this issue in the new PR.

**Comment by tealice** [comment]
@josephholsten could you review https://github.com/sous-chefs/mysql/pull/579?

**Comment by tealice** [comment]
Created a new PR with an updated branch
