### ISSUE TITLE
MySQL 5.7 on Ubuntu 14.04

### ISSUE THREAD

**Issue by StyleT** [sous-chefs/mysql#413]
Currently seems that this setup of MySQL <--> Ubuntu is unsupported in cookbook. It would be great for me to have this feature in cookbook.
It's definitely possible: http://www.devopsservice.com/installation-of-mysql-server-5-7-on-ubuntu-14-04/

**Comment by fawzyj** [comment]
+1

**Comment by tas50** [comment]
At the moment we're installing from the distro repos. We could potentially switch to upstream repos on Ubuntu as well which would enable this.

**Comment by AdrianCohea** [comment]
With a few changes it's possible to install from the upstream Oracle MySQL apt repository. I have an example of the work in my pull, which Phil Mocek helped me with.

**Comment by ramereth** [comment]
We are no longer supporting Ubuntu 14.04.
