### ISSUE TITLE
Warn Redhat needs selinux::disabled instead of can't find ./mysql/plugin.frm

### ISSUE THREAD

**Issue by mrjcleaver** [sous-chefs/mysql#417]
I note #305 has been closed and that RedHat platforms need selinux::disabled

Per https://github.com/afklm/jira/issues/71 - there is no catch of this  - instead errors exhibit symptoms that MySQL "can't find file".

**Comment by nkadel-skyhook** [comment]
Look in /var/log/audit/audit.log, if the auditd is running. You'll see the errors there.

In the very short term, selinux::permissive is enough to allow mysql to start, and to get logs of errors for fixing the issue.. But turning off SELinux is much like the pupular directions set up a "mysqldump --tab" directories with 777 permissions: it workd, but it's a gross security problem.

The appropriate changes to set up MySQL repository directories with the right SELinux permissions  are documented at https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Confined_Services/sect-Managing_Confined_Services-MySQL-Configuration_Examples.html. I don't have time right now to submit a patch, but that's where to start.
