### ISSUE TITLE
mysql postinst fails after running apt-get upgrade

### ISSUE THREAD

**Issue by sauberia** [sous-chefs/mysql#466]
### Cookbook version

7.1.1
### Chef-client version

12.10.24
### Platform Details

Ubuntu 16.04.1 LTS
### Scenario:

Attempt to upgrade the mysql-server-5.7 package
### Steps to Reproduce:

My recipe is as follows:

``` ruby
  mysql_service 'default' do
    initial_root_password 'changeme'
    action [:create, :start]
  end

  mysql_client 'default' do
    action :create
  end
```

This all worked as expected.

A few weeks later I ran apt-get upgrade which didn't complete as the mysql-server-5.7.postinst  script fails.
### Expected Result:

The mysql-server-5.7 package is successfully upgraded.
### Actual Result:

mysql-server-5.7.postinst fails during the upgrade process with the following output:

```
  + mysql_upgrade --defaults-file=/etc/mysql/debian.cnf
  mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
  Upgrade process encountered error and will not continue.
  + result=11
  + '[' 11 -ne 0 -a 11 -ne 2 ']'
  + echo 'mysql_upgrade failed with exit status 11'
  mysql_upgrade failed with exit status 11
  + exit 1
  dpkg: error processing package mysql-server-5.7 (--configure):
   subprocess installed post-installation script returned error exit status 1
  Errors were encountered while processing:
   mysql-server-5.7
  E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mansona** [comment]
I have the exact same issue. Do we have any idea of a workaround for this?

**Comment by mansona** [comment]
After a bit of investigation it seems that this is an apparmor issue

```
-- Subject: Unit mysql-default.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mysql-default.service has begun starting up.
Sep 08 15:56:07 torontossc-dev audit[7531]: AVC apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/etc/mysql-default/my.cnf" pi
Sep 08 15:56:07 torontossc-dev mysqld[7531]: mysqld: [ERROR] Could not open required defaults file: /etc/mysql-default/my.cnf
Sep 08 15:56:07 torontossc-dev mysqld[7531]: mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

Once you stop apparmor you get further down the installation path but there are still some issues. I would recommend rolling back to version 7.2.0 until these other issues are fixed

**Comment by klyonrad** [comment]
> I would recommend rolling back to version 7.2.0 until these other issues are fixed

The issue creator noted that the problem applies to Cookbook Version 7.1.1...

**Comment by mansona** [comment]
@klyonrad in that case these are 2 separate issues, his workaround would be to just disable apparmor 👍

**Comment by wilb** [comment]
Putting apparmor into complain mode for the service doesn't help - the post installation script gets into a mess. 

 # aa-complain /usr/sbin/mysqld
  Setting /usr/sbin/mysqld to complain mode.

```
# apt-get install -f 
Setting up mysql-server-5.7 (5.7.16-0ubuntu0.16.04.1) ...
insserv: warning: current start runlevel(s) (empty) of script `mysql' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `mysql' overrides LSB defaults (0 1 6).
dpkg: error processing package mysql-server-5.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 mysql-server-5.7
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Tealc002** [comment]
What helped for me was running 'systemctl enable mysql' and running 'apt-get install -f' again.

**Comment by sauberia** [comment]
@Tealc002 I can confirm that works for me. I can finally, successfully run apt-get update.

**Comment by wilb** [comment]
Doesn't work for me - I think the above is likely to work if you've still got enough remnants of a packaged install hanging around for the postinst script to run through, connect to a running instance and think it's managed to upgrade itself successfully.

**Comment by wilb** [comment]
OK, had to get dirty to make this work. Apparmor definitely wasn't helping matters either.

```apt install apparmor-utils
aa-complain /usr/sbin/mysqld
cd /tmp/
apt-get download mysql-server-5.7
dpkg --unpack mysql-server-5.7_5.7.16-0ubuntu0.16.04.1_amd64.deb
rm /var/lib/dpkg/info/mysql-server-5.7.postinst
dpkg --configure mysql-server-5.7
service mysql-default restart```

```Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 15
Server version: 5.7.16-0ubuntu0.16.04.1 (Ubuntu)```

Given the cookbook avoids the packaged installation mechanisms as much as possible I don't think there is too much harm in not having the postinst script run on a minor increment.

**Comment by deragon** [comment]
This looks like related to [Launchpad bug #1592669](https://bugs.launchpad.net/ubuntu/+source/mysql-5.7/+bug/1592669).

**Comment by zjuchenyuan** [comment]
When I try `systemctl enable mysql`

```
# systemctl enable mysql
Synchronizing state of mysql.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable mysql
Failed to execute operation: Invalid argument
```

then, I try `systemctl disable mysql`, and then `systemctl enable mysql` worked!

finally, run 'apt-get install -f' again.

**Comment by danielristic** [comment]
Same for me on mysql cookbook version 7.1.2 and Ubuntu 16.04.1 LTS: postinstall script fails, but mysql still seems to be updated to the latest version so besides throwing an error on subsequent apt-get upgrade commands this seems mostly harmless.

Not feeling like messing up to much with it as it could break my production environment, but I would appreciate any update on this!

**Comment by ramereth** [comment]
@danielristic is this still happening with the latest version?
