### ISSUE TITLE
/etc/init.d/mysqld getting created along with /etc/init.d/mysql-sample if sysvinit is used

### ISSUE THREAD

**Issue by AjeetK** [sous-chefs/mysql#506]
### Cookbook version
8.2

### Chef-client version
12.18.31

### Platform Details
centos-6.8

### Scenario:
Following recipe results into creation of `/etc/init.d/mysqld` and `/etc/init.d/mysql-sample`
```
include_recipe 'yum-mysql-community::mysql55'
mysql_service 'sample' do
  port '3307'
  version '5.5'
  run_user 'mysql'
  data_dir '/vol/mysql'
  service_manager 'sysvinit'
  action [:create, :start]
end
```

### Steps to Reproduce:
use the above recipe

### Expected Result:
`/etc/init.d/mysqld` should not get created as if somebody runs `sudo service mysqld start` then one more mysql process will start along with a process already running with `/etc/init.d/mysql-sample`.

### Actual Result:
Either `/etc/init.d/mysqld` or `/etc/init.d/mysql-sample` should get created.

**Comment by nkadel-skyhook** [comment]
The "/etc/init.d/mysqld" is probably created by the original RPM or similar package installation. It should be flushed or ideally disabled by chef if it exists from an RPM installation. at least until or unless the "crate an instance of mysql" is reconfigured to allow it to not have a null instance name.

**Comment by ramereth** [comment]
We are no longer supporting operating systems which still use sysvinit.
