### ISSUE TITLE
Systemd does not honor init file limits in centos 7

### ISSUE THREAD

**Issue by geleman** [sous-chefs/mysql#509]
The template for systemd needs to include LimitNOFILE=[attributevalue]
Systemd does not honor the file limits you may set in your my.cnf file and will default to 1024
A consideration might also need to be done to increase Max Locked Memory

https://github.com/chef-cookbooks/mysql/blob/master/templates/default/systemd/mysqld.service.erb

**Comment by geleman** [comment]
another fix could be to allow for the cookbook allowed to be changed here 
https://github.com/chef-cookbooks/mysql/blob/master/libraries/mysql_service_manager_systemd.rb#L40-L56

**Comment by ramereth** [comment]
Duplicate of #533
