### ISSUE TITLE
Add mysql_database and mysql_database_user resources to this cookbook

### ISSUE THREAD

**Issue by cringdahl** [sous-chefs/mysql#522]
As the database cookbook is meant to be deprecated, I'm requesting `mysql_database` and `mysql_database_user` be added to the mysql cookbook. This would help MySQL folks get off the database cookbook faster, which in turn would help database go to a farm upstate, where it can run and play and always be happy.

**Comment by monokal** [comment]
+1

**Comment by daverogers** [comment]
"Feature Request" being full-on deprecation of the database library with only the passing notion that Chef might get around to implementing those features into their provider cookbooks? It's a difficult thing to explain to my company's decision makers, why we should stick with Chef, when one of their own packages we depended on is dropped in favor of, apparently, nothing. Maybe I'm missing something though, and someone could clarify why I'm completely wrong. :man_facepalming:

**Comment by nkadel-skyhook** [comment]
Please read why it was deprecated, at https://github.com/chef-boneyard/database

Integrating the mysql specific database operations into the primary mysql cookbook makes logical sense. It introduces a lot of potential complexity, such as handling non-encrypted passwords more safely and complex database setups and access management that may be better factored into a "mysql-database" cookbook, forked from "database".

**Comment by heaven** [comment]
Unfortunately, reading why it is deprecated doesn't help. And why were issues disabled there? I have an error and don't really have a place where I could share the problem and my findings.

**Comment by daverogers** [comment]
Yeah, I ended up just running mysql commands directly in my recipe and dumped the old database cookbook altogether.

```ruby
execute "Create database users" do
    command "mysql -e \"CREATE DATABASE users\""
end
````

**Comment by daften** [comment]
The way it should be done (in order)

1. add the resources on a new major version of the mysql cookbook
2. Mark the database cookbook as deprecated

Not the other way around with "adding the resources" being done somewhere in the future ...

**Comment by mengesb** [comment]
@roylindauer not likely this is to be implemented here honestly. Managing DBs is out of scope for this cookbook - as it's meant to manage the service/application.

If you'd like to message me on the community chef slack in the sous-chef channel I'd be more than happy to help you through how I'm doing it currently in production.

This issue should likely be closed/locked given it's age and I don't think there's anything on the roadmap. Someone else from the team please feel free to correct me.

As always, @ronabop, PRs are welcome!
