### ISSUE TITLE
selinux requirements refinement

### ISSUE THREAD

**Issue by javornikolov** [sous-chefs/mysql#523]
### Cookbook version
8.3.1

### Chef-client version
13

### Platform Details
CentOS 7
MySQL 5.7 (include_recipe 'yum-mysql-community::mysql57')

### Scenario:
mysql_service start would fail

### Steps to Reproduce:
Given a CentOS 7 box with selinux enforced
And `recipe[selinux::disabled]` is included in the Chef run
When after that the following is executed during the same Chef run 
``` ruby
mysql_service 'default' do
  version '5.7'
  bind_address 'localhost'
  initial_root_password '***'
  action [:create, :start]
end
```

Then it fails to start because selinux is still not disabled (as per selinux cookbook - that needs reboot).

### Workaround:
``` ruby
selinux_state 'SELinux Permissive Temporary' do
  temporary true
  action :permissive
end

selinux_state 'SELinux Permissive Permanent after reboot' do
  temporary false
  action :permissive
end
```
### Request:
It's good to either refine the requirements note or change selinux cookbook itself so that the currently listed requirements are suffient.

**Comment by MitchellJThomas** [comment]
I'm interested in this workaround/fix.  When should I expect it to be released?
