### ISSUE TITLE
"mysqladmin stop" is not used, contributes to My

### ISSUE THREAD

**Issue by nkadel-skyhook** [sous-chefs/mysql#532]
### Cookbook version
7.2.0

### Chef-client version
12.10.24

### Platform Details
CentOS 6, MySQL 5.7

### Scenario:
Mysql slaves need to restart gracefully, with no errors.

### Steps to Reproduce:
Install a MySQL 5.7 instance with the current or recent chef cookbooks.
Restart MySQL a dozen times, with a busy upstream MySQL master and a local slave.

### Expected Result:
Working MySQL slave status with no errors.

### Actual Result:
Look for "duplicate entry errors" in reports of the MySQL slave status, which wedge the MySQL slave. MySQL slave intermittently fails with duplicate entry error.

The correct workaround would seem to be to use the "mysqladmin stop" command, pointed to the particular MySQL instance.

**Comment by iennae** [comment]
It's unclear what part of the cookbook is giving you a problem based on the description here. Can you expand where you think the mysqladmin stop should go? In general a database that is under load will take time to gracefully stop so a rapid stop/start to the primary database can cause problems.

**Comment by nkadel-skyhook** [comment]
The templates/sysvinit/mysqld.erb init script is what I seem to be encountering issues with. The use of the "kill" command in the stop and start functions makes no attempt to use the more graceful "mysqladmin stop" command.  The slave status on my servers is frequently updated, and the "kill" command issued to the running mysqld is not terminating on its own. It hits the 900 second wait period, and then gets killed with extreme prejudice.

The working theory I'm pursuing is that applying the 'kill' on the PID is too brutal, and using "mysqladmin stop" will more gracefully complete and stop mysql slave operations. So I'm thinking to add a step to the "stop" operations, just before the "kill" is issued, with a command like
* mysqladmin  --defaults-file=/etc/mysql-[instance]/my.cnf  stop

If no one objects, I can try to branch and submit a pull request for this. I can't do this for systemd right now.

**Comment by nkadel-skyhook** [comment]
I'm testing if this makes a difference. It's not clear to me that the "mysqladmin shutdown" actually does more of a clean shutdown than the "kill $PID" effectively does. My testing work is over at https://github.com/nkadel-skyhook/nkadel-mysql-cookbook/tree/nkadel-mysqladmin

**Comment by iennae** [comment]
That's where I got to when I was testing it. The problem is that in a high use system, the graceful stop isn't so graceful for primary/secondary configurations. I'm interested to see where this leads. Are you heading to any of the US Summits next week?

**Comment by ramereth** [comment]
We no longer support EL6 and sysvinit.
