### ISSUE TITLE
Ability to setup a service without providing instance name

### ISSUE THREAD

**Issue by heaven** [sous-chefs/mysql#536]
It looks like this is causing us lots of overhead with no benefits, why do we need to set up MySQL at a custom location when we only run one instance per machine?

It would be just great to be able to do:
```ruby
mysql_service do
  port node['mysql']['port']
  version node['mysql']['version']
  initial_root_password node['mysql']['server_root_password']
  action [:create, :start]
end
```

**Comment by ConfusedVorlon** [comment]
amongst other things - the custom location breaks upgrades on Ubutntu as apt-get can't start/stop the service in the way it expects
