### ISSUE TITLE
Recipe compile error "uninitialized constant MysqlCookbook::Helpers" under Vagrant

### ISSUE THREAD

**Issue by DenisSmirnov92** [sous-chefs/mysql#540]
### Cookbook version
8.5.1

### Chef-client version
13.7.16

### Platform Details
Ubuntu 14.04 x86_64

### Scenario:
Trying to setup project via Vagrant

### Steps to Reproduce:
run "vagrant provision"

### Expected Result:
Chef successfully completed.

### Actual Result:

`==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: NameError
==> default: ---------
==> default: uninitialized constant MysqlCookbook::Helpers
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:7:in `<class:MysqlClient>'
==> default: 
==> default:   /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:6:in `<class:Provider>'
==> default: 
==> default:   /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:5:in `<class:Chef>'
==> default: 
==> default:   /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:4:in `<top (required)>'
==> default: 
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_client.rb:
==> default: 
==> default: 
==> default: 
==> default:   1:  require 'chef/provider/lwrp_base'
==> default: 
==> default:   2:  require_relative 'helpers'
==> default: 
==> default:   3:  
==> default: 
==> default:   4:  class Chef
==> default: 
==> default:   5:    class Provider
==> default: 
==> default:   6:      class MysqlClient < Chef::Provider::LWRPBase
==> default: 
==> default:   7>>       include MysqlCookbook::Helpers
==> default: 
==> default:   8:  
==> default: 
==> default:   9:        use_inline_resources if defined?(use_inline_resources)
==> default: 
==> default:  10:  
==> default: 
==> default:  11:        def whyrun_supported?
==> default: 
==> default:  12:          true
==> default: 
==> default:  13:        end
==> default: 
==> default:  14:  
==> default: 
==> default:  15:        action :create do
==> default: 
==> default:  16:          # From helpers.rb
==> default: 
==> default: 
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.7.16
==> default: 
==> default: platform=ubuntu
==> default: 
==> default: platform_version=14.04
==> default: 
==> default: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
==> default: 
==> default: program_name=chef-solo worker: ppid=11022;start=16:47:23;
==> default: 
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2018-01-26T16:47:31+00:00] ERROR: Running exception handlers
==> default: [2018-01-26T16:47:31+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2018-01-26T16:47:31+00:00] ERROR: Exception handlers complete
==> default: [2018-01-26T16:47:31+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 07 seconds
==> default: [2018-01-26T16:47:31+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-01-26T16:47:31+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-01-26T16:47:31+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-01-26T16:47:31+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-01-26T16:47:31+00:00] ERROR: uninitialized constant MysqlCookbook::Helpers
==> default: [2018-01-26T16:47:31+00:00] ERROR: uninitialized constant MysqlCookbook::Helpers
==> default: [2018-01-26T16:47:31+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> default: [2018-01-26T16:47:31+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

`

**Comment by esellin** [comment]
Same error here with mysql 8.5.1 and chef 13.8.0

helpers.rb provides MysqlCookbook::HelpersBase
but provider_mysql_client.rb tries to include MysqlCookbook::Helpers

**Comment by esellin** [comment]
The file provider_mysql_client.rb does not exist anymore in version 8.x.x of the cookbook.

Make sure you don't have old files from a previous version 7.x.x of the cookbook lying around.

If you're using Berkshelf, try to delete its cache (~/.berkself).

If you're copying everything to your target server, and then use chef zero (-z), look over there as well.
