### ISSUE TITLE
How to override systemd service template?

### ISSUE THREAD

**Issue by heaven** [sous-chefs/mysql#546]
We need to add `LimitNOFILE=8192` to the service template, how do we do so? When trying to change the cookbook for the resource it is not defined.

**Comment by nadobando** [comment]
same here

**Comment by jonathanza** [comment]
We need this functionality too. 
@heaven @nadobando were you able to find a solution to this.

**Comment by heaven** [comment]
@jonathanza I don't remember what exactly solved this for us, but this is what I found in my cookbook searching by `LimitNOFILE`:

```ruby
template "/etc/systemd/system/mysql-#{params[:name]}.service.d/limit_nofile.conf" do
  source 'systemd/limit_nofile.conf.erb'
  owner 'root'
  group 'root'
  mode '0644'
  action :create
end
```

Template content:

```
[Service]
LimitNOFILE=8192
```

**Comment by jonathanza** [comment]
> @jonathanza I don't remember what exactly solved this for us, but this is what I found in my cookbook searching by `LimitNOFILE`:
> 
> ```ruby
> template "/etc/systemd/system/mysql-#{params[:name]}.service.d/limit_nofile.conf" do
>   source 'systemd/limit_nofile.conf.erb'
>   owner 'root'
>   group 'root'
>   mode '0644'
>   action :create
> end
> ```
> 
> Template content:
> 
> ```
> [Service]
> LimitNOFILE=8192
> ```

Thanks, this strategy worked great.

**Comment by damacus** [comment]
Closing as resolved. 

Thanks everyone!

**Comment by ifeltsweet** [comment]
Thanks @heaven. This really should be part of this cookbook.
