### ISSUE TITLE
Upgrading from version 5.6.3

### ISSUE THREAD

**Issue by danielristic** [sous-chefs/mysql#549]
I'm trying to provision a server with a Chef project that relied on an older version of the mysql cookbook (5.6.3). As this particular version is not compatible with anything newer that Ubuntu 14.04, I tried updating to the latest version (8.5.1) which lead to a `RecipeNotFound` error.

I understand that the mysql cookbook no longer provides recipes and is a library only cookbook now, but it's really not clear how I'm supposed to edit my chef project to do what the older version did and It's surprisingly difficult to find any explanation on how to do that: I've only found a few tutorials but they seem outdated as they rely on the now deprecated `database` cookbook.

Currently I have a `mysql-server` role defined in my chef project that has "mysql::client" and "mysql::server" in its `run_list` section. Am I missing something or is my only option to create a wrapper cookbook like the documentation seems to suggest? If so, is there any publicly available cookbook built on top of this one to simply install mysql client and server?

**Comment by koertkuipers** [comment]
in so far i know the message when they went from 5.x to 6.x was that there would be no upgrade path. i believe the suggestion was to keep using 5.x (not realistic) or do a complete reinstall of the server (again not realistic).
the focus of 6.x (or was it 7.x? i forgot) seemed to be to switch to resources, with the main benefit being that you could install multiple mysql instances on same machine, which goes against any recommendation for how you are supposed to use mysql. where this silly idea came from i still dont know.

we have been through plenty of cookbooks upgrades over an 8 year period, and mysql 5 to newer still ranks as the worst one in my history of upgrades.
