### ISSUE TITLE
My SQl Install error with this cookbook

### ISSUE THREAD

**Issue by AnishAnil** [sous-chefs/mysql#550]
### Cookbook version
8.5.1

### Chef-client version
Starting Chef Client, version 14.0.202

### Platform Details
uname -a
Linux ip-172-31-18-16 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Scenario:
Trying to run the community cookbook to install n configure the mysql

### Steps to Reproduce:
download the cookbook
1> knife cookbook site download mysql
2> unzip & untar it
 3> Run --> knife cookbook upload mysql
4> chef-generate cookbook mysqlcommunity
5> make changes to metadat.rb file for mysqlcommunity and add the following line
depends 'mysql', '~> 8.0'
6> open the recipe -->default.rb and add the following lines

**********
# Recipe:: default
#
# Copyright:: 2018, The Authors, All Rights Reserved.
mysql_service 'foo' do
  port '3306'
  version '5.7.21'
  initial_root_password 'change me'
  action [:create, :start]
end
**********
7> knife cookbook uplaod mysqlcommunity
8> Add the recipe to the node machin
9> login to the Node and run chef-client and it simply fails with the error:

It fails with errors
*********
Starting Chef Client, version 14.0.202
resolving cookbooks for run list: ["mysqlcommunityedition"]
Synchronizing Cookbooks:
  - mysqlcommunityedition (0.1.0)
  - mysql (8.5.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: mysqlcommunityedition::default
  * mysql_service[foo] action create
    * mysql_server_installation_package[foo] action install
      * apt_package[mysql-community-server] action install
        * No candidate version available for mysql-community-server
        ================================================================================
        Error executing action `install` on resource 'apt_package[mysql-community-server]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for mysql-community-server
*********

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

      ================================================================================
      Error executing action `install` on resource 'mysql_server_installation_package[foo]'
      ================================================================================

      Chef::Exceptions::Package
      -------------------------
      apt_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb

       36:           install = mysql_server_installation(new_resource.name, &block)
       37:         when 'package'

      Compiled Resource:

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
It should have installed the mysql server

**Comment by AnishAnil** [comment]
Full Error:

Starting Chef Client, version 14.0.202
resolving cookbooks for run list: ["mysqlcommunityedition"]
Synchronizing Cookbooks:
  - mysqlcommunityedition (0.1.0)
  - mysql (8.5.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: mysqlcommunityedition::default
  * mysql_service[foo] action create
    * mysql_server_installation_package[foo] action install
      * apt_package[mysql-community-server] action install
        * No candidate version available for mysql-community-server
        ================================================================================
        Error executing action `install` on resource 'apt_package[mysql-community-server]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for mysql-community-server

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb

         17:       package new_resource.package_name do
         18:         version new_resource.package_version if new_resource.package_version
         19:         options new_resource.package_options if new_resource.package_options
         20:         notifies :install, 'package[perl-Sys-Hostname-Long]', :immediately if platform_family?('suse')
         21:         notifies :run, 'execute[Initial DB setup script]', :immediately if platform_family?('suse')
         22:         action :install
         23:       end
         24:

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb:17:in `block in <class:MysqlServerInstallationPackage>'

        apt_package("mysql-community-server") do
          package_name "mysql-community-server"
          action [:install]
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "mysqlcommunityedition"
        end

        System Info:
        ------------
        chef_version=14.0.202
        platform=ubuntu
        platform_version=16.04
        ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
        program_name=/usr/bin/chef-client
        executable=/opt/chef/bin/chef-client


      ================================================================================
      Error executing action `install` on resource 'mysql_server_installation_package[foo]'
      ================================================================================

      Chef::Exceptions::Package
      -------------------------
      apt_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb

       36:           install = mysql_server_installation(new_resource.name, &block)
       37:         when 'package'

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb:36:in `installation'

      mysql_server_installation_package("foo") do
        action [:install]
        default_guard_interpreter :default
        declared_type :mysql_server_installation
        cookbook_name "mysqlcommunityedition"
        package_name "mysql-community-server"
      end

      System Info:
      ------------
      chef_version=14.0.202
      platform=ubuntu
      platform_version=16.04
      ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      program_name=/usr/bin/chef-client
      executable=/opt/chef/bin/chef-client


    ================================================================================
    Error executing action `create` on resource 'mysql_service[foo]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    mysql_server_installation_package[foo] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Chef::Exceptions::Package: apt_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mysqlcommunityedition/recipes/default.rb

      6: mysql_service 'foo' do
      7:   port '3306'
      8:   version ''
      9:   initial_root_password 'change me'
     10:   action [:create, :start]
     11: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/mysqlcommunityedition/recipes/default.rb:6:in `from_file'

    mysql_service("foo") do
      action [:create, :start]
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name "mysqlcommunityedition"
      recipe_name "default"
      port "3306"
      initial_root_password "change me"
    end

    System Info:
    ------------
    chef_version=14.0.202
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client


Running handlers:
[2018-04-18T09:23:01+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-18T09:23:01+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2018-04-18T09:23:02+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-04-18T09:23:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-18T09:23:02+00:00] FATAL: Chef::Exceptions::Package: mysql_service[foo] (mysqlcommunityedition::default line 6) had an error: Chef::Exceptions::Package: mysql_server_installation_package[foo] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Chef::Exceptions::Package: apt_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server

**Comment by Sam-Martin** [comment]
I had a similar issue with Debian 9. Should work if you specify the package name manually. 
e.g.
```ruby
mysql_service 'proftpd' do
  port '3306'
  package_name 'mysql-server'
  version '*'
  initial_root_password 'change me'
  action [:create, :start]
end
```

**Comment by lashomb** [comment]
I get this even with trying to declare package_name.

**Comment by ramereth** [comment]
@AnishAnil @lashomb @Sam-Martin are you still having this problem with the current version of the cookbook?
