### ISSUE TITLE
Travis CI not picking up pull requests

### ISSUE THREAD

**Issue by p8** [sous-chefs/mysql#562]
It seems Travis is not running builds for pull requests after moving the repo to sous-chefs.
See the latest pull requests:
https://github.com/sous-chefs/mysql/pull/561
https://github.com/sous-chefs/mysql/pull/559

**Comment by damacus** [comment]
Right, I don't exactly know what caused that, but forcing Travis to rewrite the webhooks seems to have fixed it. 

Try pushing another commit to each of those PRs and it should kick it into life. Thanks for letting me know!
