### ISSUE TITLE
SystemD + Percona MySQL 5.7 on RHEL 7.5 start issues

### ISSUE THREAD

**Issue by mengesb** [sous-chefs/mysql#565]
# Cookbook version

- 8.5.1
- systemd template: https://github.com/sous-chefs/mysql/blob/master/templates/default/systemd/mysqld.service.erb

# Chef-client version

13.8.5

# Platform Details

RHEL 7.5

# Scenario:

Wrap this cookbook to install Percona MySQL

# Steps to Reproduce:

normal usage

# Expected Result:

service starts

# Actual Result:

service fails to start

# Notes

https://github.com/awm086/mysql/blob/1121ad6aded280aa5bb15fe74273eda5c4e364c5/templates/default/systemd/mysqld.service.erb#L11

Seems that for RHEL7 and using the Percona MySQL 5.7 binaries ... the `/usr/share/mysql` path is nno created... therefore nothing here exists. So the `ExecStartPre` fails and the instance doesn't come up.

Now while I am using the 8.5.1 cookbook version with the master version of the mysql service template, I had to use a `Chef.event_handler` to hack it in... so if you contact me in the sous-chefs chat I can go over the exact code where I spliced this in. If this is explicitly not handled because this is Percona MySQL instead of MySQL then that's OK... but

**Comment by swistak35** [comment]
I've encountered the same issue (Percona 5.6 and Ubuntu) and fixed it by adding a `template` resource with an almost empty **executable** file (`#!/bin/bash` as only source, for some reason systemd failed with completely empty file without shebang) for that path.

**Comment by mengesb** [comment]
closing, likely not important enough to address

**Comment by ramereth** [comment]
FWIW we recently updated the percona cookbook quite a bit and I believe it includes this fix in there. This cookbook should not deal with percona IMO.
