### ISSUE TITLE
Sysinit script does not start mysql after reboot

### ISSUE THREAD

**Issue by josacar** [sous-chefs/mysql#595]
### :speaking_head: Foreword

Hi,

`mysql_service` provider with `sysvinit` creates a SysV that fails to boot when system is restarted.

## :ghost: Brief Description

The service created `mysql_service` with `sysvinit` provider fails to start after a system reboot.

## :pancakes: Cookbook version

8.5.1

## :woman_cook:  Chef-Infra Version

Any Chef version

## :tophat: Platform details

Any distribution when sysvinit is used

## Steps To Reproduce

1. Use `sysvinit` init provider in `mysql_service` and set service to be started at boot
2. Reboot the instance
3. Service fails to start

## :police_car: Expected behavior

Service should start

## :heavy_plus_sign: Additional context

The service fails to start because `/run` is cleaned after every reboot, so `/run/mysql-SERVICE` is deleted and `pid` and `socket` files cannot be placed inside as the parent directory does not exist.

Thinking about to fix this, 3 alternatives come out my mind:

- Let mysql create this missing directory ( /run should be with sticky bit like /tmp does ) or run as `root`
- Change the `socket` and `pid_file` attributes is not possible if `/run` is not `777`
- Override the template file ( not possible ) or fix it and create those directories before starting `mysql`

Thoughts?

**Comment by josacar** [comment]
The third option is basically is to port [this](https://github.com/sous-chefs/mysql/blob/master/templates/default/upstart/mysqld.erb#L18-L19) to the `sysvinit` template

**Comment by ramereth** [comment]
We are focusing only on supporting systemd moving forward.
